config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  #ユーザーのルート作成
  resources :users
  #スケジュールのルート作成
  resources :schedules

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map_api.rb
class MapApi < ApplicationRecord
    # 変数を初期化
    def initialize(schedule_param)
        @schedule_param = schedule_param
    end
    
    def uri
        # フォームから飛んできた住所をエスケープして変数に格納
        d_address = URI.encode_www_form({d_address: @schedule_param})
        a_address = URI.encode_www_form({a_address: @schedule_param})
        # Geocoding APIを叩く
        URI.parse("https://maps.googleapis.com/maps/api/directions/json?origin=#{d_address}&destination=#{a_address}&key=AIzaSyAhijDhCRPrT1XrK8ygyqMZsCzIWSdqpow")
    end

    def result
        # 返ってきたJSONをパースしてapi_response という変数に格納
        api_response = Net::HTTP.get_response(uri)
        response_body = JSON.parse(api_response.body)
        
    end
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :schedule
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user
    attachment :image
    

    
    has_many :schedule_hoteldates, dependent: :destroy
    accepts_nested_attributes_for :schedule_hoteldates, allow_destroy: true
    
    with_options presence: true do
        validates :num_p
        validates :fuel
        validates :fuel_economy
        validates :title
        validates :start_date
        validates :end_date

    end


end

app/models/schedule_driveplan.rb
class ScheduleDriveplan < ApplicationRecord
  belongs_to :schedule_hoteldate

  geocoded_by :address # addressカラムを基準に緯度経度を算出する。
  after_validation :geocode # 住所変更時に緯度経度も変更する。

  def self.sum_f_price
    sum_price = 0
    sum(:f_price)
  end
  
  with_options presence: true do
    validates :d_address
    validates :a_address
    validates :d_name
    validates :a_name
  end
  
end

app/models/schedule_hoteldate.rb
class ScheduleHoteldate < ApplicationRecord
  attachment :image
  belongs_to :schedule


  def self.sum_price
    sum(:hotel_price)
  end

  has_many :schedule_driveplans, dependent: :destroy
  accepts_nested_attributes_for :schedule_driveplans, allow_destroy: true

  with_options presence: true do
    validates :hotel_date
    validates :start_time
    
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # デフォルトの設定に、:omniauthable以下を追加
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド       
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  attachment :profile_image

  has_many :schedules, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def after_sign_in_path_for(resource)
        user_path(current_user)
    end

    def after_sign_up_path_for(resource)
        user_path(current_user)
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @schedule = Schedule.new
    @place = Place.new
    @place = Place.all
    
    
    
  end
  
  def create
    @schedule = current_user.schedules.build(schedule_params)
    
    if @schedule.save
      redirect_to schedule_path(@schedule), notice: "スケジュールを保存しました。"
    else
      render :new
    end
  end

  def index
    @schedules = Schedule.all.order(id: "DESC")
    
  end

  def show
    @schedule = Schedule.find(params[:id])  
    
  end

  def edit
    @schedule = Schedule.find(params[:id])
    if @schedule.user != current_user
        redirect_to schedules_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to schedule_path(@schedule), notice: "スケジュールを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy  
    redirect_to user_path(schedule.user), notice: "スケジュールを削除しました。"
  end

  
  
  private
  def schedule_params
    params.require(:schedule).permit(:title, :start_date, :end_date, :num_p, :image, :address,
                                    :fuel, :fuel_economy,
                                    schedule_hoteldates_attributes:[:id, :schedule_id, :hotel_date,
                                    :hotel_name, :hotel_url, :imgage, :hotel_price, :start_time, :_destroy, 
                                    schedule_driveplans_attributes:[:id, :schedule_hoteldate_id,
                                    :start_time, :address, :price, :d_address, :a_address, :distance, :duration, :d_name,
                                    :a_name, :f_price, :s_time, :meal_price, :name, :_destroy]]
                                    ).merge(user_id: current_user.id)
    
  end
  

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      callback_for(:facebook)
    end
  
    def google_oauth2
      callback_for(:google)
    end
  
    # common callback method
    def callback_for(provider)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    #Userモデルのユーザ情報をすべて@users変数に代入
    @users = User.all
  end

  def show
    #user一人のidを見つけて@userに代入
    @user = User.find(params[:id])
  end

  def edit
    #user一人のidを見つけて@userに代入
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    #ユーザー情報を更新しユーザー詳細画面に遷移
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!--
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travelapp</title>
    <% csrf_meta_tags %>
    <% csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <% stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="top-wrapper">
      <h1>DRIVETRAVELAPP</h1>
      <p>Travelappは旅行スケジュール作成アプリです。</p>
      <div class="message-wrapper">
        <span class="btn message"><% link_to "スケジュールを作成", new_schedule_path %></span>
      </div>
    </div>
  </body>
</html>
-->
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">DriveTravelapp</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
        <div class="top-wrapper">
            <div class="container1">
                <h1>DRIVE TRAVEL APP.</h1>
                <p>DRIVE TRAVEL APPはあなたのドライブ旅行を快適にするためのスケジュール管理アプリです。</p>
                
            </div>
        </div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">DriveTravelapp</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <div class="navbar-item">
                  <%= link_to "スケジュール作成", new_schedule_path, class: "navbar-item button is-warning is-light" %>
                </div>
                <div class="navbar-item">
                  <%= link_to "スケジュール一覧", schedules_path, class: "navbar-item button is-warning is-light" %>
                </div>
                <div class="navbar-item">
                  <%= link_to "ユーザー一覧", users_path, class: " button is-warning is-light" %>
                </div>
                <div class="navbar-item">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </div>
                <div class="navbar-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <div class="navbar-item">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </div>
                <div class="navbar-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/schedules/_schedule_driveplan_fields.html.erb
<div class="nested-fields">
    <div class="planbox1">
        <div class = "text-left">
            <table align="center" >
                <tr>
                    <td>
                        <%= f.label :d_name, "出発点の名前", class: "label" %>
                        <%= f.text_field :d_name, size: "15", class: "form-input" %>
                    </td>
                    <td>
                        <%= f.label :d_address, "出発地点の詳細な住所", class: "label" %>
                        <%= f.text_field :d_address, size: "30", class: "form-input" %>
                    </td>
                </tr>
            </table>
            <table align="center" >
                <tr>
                    <td>
                        <%= f.label :d_name, "到着点の名前", class: "label" %>
                        <%= f.text_field :a_name, size: "15", class: "form-input" %>
                    </td>
                    <td>
                        <%= f.label :d_address, "到着地点の詳細な住所", class: "label" %>
                        <%= f.text_field :a_address, size: "30", class: "form-input" %>
                    </td>
                </tr>
            </table>
            <%= f.label :f_price, "高速料金", class: "label" %>
            <%= f.number_field :f_price, size: "10" %>
            <%= f.label :s_time, "滞在時間", class: "label" %>
            <%= f.time_field :s_time, size: "10" %> 
            <%= f.select :name, [["観光", "観光"], ["食事", "食事"], ["宿泊", "宿泊"], ["休憩", "休憩"]], include_blank: "ジャンルを選択" %>
            <%= f.label :meal_price, "観光または食事にかかる料金", class: "label" %>
            <%= f.number_field :meal_price, size: "30" %>
        </div>
        <div class="btn-right">
            <%= link_to_remove_association "プランを削除",f , class: "btn btn-secondary btn-block" %>
        </div>
    </div>
</div>

app/views/schedules/_schedule_hoteldate_fields.html.erb
<div class="nested-fields">
    <div class="row mx-auto">
        <div class="datebox">
            <div class="btn-right">
                <%= link_to_remove_association "日付を削除", f, class: "btn btn-secondary btn-block" %>
            </div>
            <%= f.label :date, "日付", class: "label" %>
            <%= f.date_field :hotel_date, class: "input", placeholder: "日付" %>
            <%= f.label :hotel_name, "宿泊先の名前", class: "label" %>
            <%= f.text_field :hotel_name, :size=>"40",class: "input", placeholder: "名前" %>
            <%= f.label :hotel_url, "宿泊先URL", class: "label" %>
            <%= f.text_field :hotel_url, :size=>"40",class: "input", placeholder: "URL" %>
            <%= f.label :hotel_price, "宿泊先の料金", class: "label" %>
            <%= f.number_field :hotel_price, :size=>"20",class: "input", placeholder: "料金" %>
            <%= f.label :start_time, "出発時間", class: "label" %>
            <%= f.time_field :start_time, :size=>"20",class: "input", placeholder: "料金" %>
            <div class="btn-right btn-margin">
                <%= link_to_add_association "プランを追加", f, :schedule_driveplans,
                class: "btn btn-secondary btn-block",
                data: {
                data_association_insertion_traversal: 'closest',
                association_insertion_method: 'append'
                }%>
            </div>
            <div class="mx-auto">
                <%= f.fields_for :schedule_driveplans do |schedule_driveplan| %>
                    <%= render "schedules/schedule_driveplan_fields", f: schedule_driveplan %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/schedules/edit.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                スケジュール編集
            </h1>
        </div>
    </div>
</section>

<% if @schedule.errors.any? %>
    <div class="notification is-danger">
        <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
        <ul>
            <% @schedule.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-6">
                <%= form_with(model: @schedule, local: true) do |f| %>
                    <div class="field">
                        <%= f.label :title, "旅のタイトル", class: "label" %>
                        <%= f.text_field :title, class: "input" %>
                    </div>
                    <div class="field">
                        <div class="form-inline">
                            <tr valign="middle" >
                                <%= f.label :body, "出発日", class: "label" %>
                                <%= f.date_field :start_date, class: "input" %>
                            </tr>
                            <tr valign="middle" >
                                <%= f.label :body, "帰着日", class: "label" %>
                                <%= f.date_field :end_date, class: "input" %>
                            </tr>
                        </div>
                    </div>
                    <div class="field">
                        <%= f.label :num_p, "旅行する人数", class: "label" %>
                        <%= f.number_field :num_p, size: 50 %>
                    </div>
                    <%= f.select :fuel_economy, [["軽自動車", 18], ["普通自動車", 15]], include_blank: "車の種類を選択" %>
                    <div class="field">
                        <%= f.label :fuel, "給油地域のガソリン代(km/L)", class: "label" %>
                        <%= f.number_field :fuel, size: 20,class: "input" %>
                    </div>
                    <div class="field">
                        <%= f.label :image, "写真", class: "label" %>
                        <%= f.attachment_field :image, class: "input" %>
                    </div>
                    <div class="plan-post">
                        <div class="recipe-ingredients">
                            <div id="detail-association-insertion-point"></div>
                            <div class="btn-right btn-adddate">
                                <%= link_to_add_association "日付を追加", f, :schedule_hoteldates,
                                class: "btn",
                                data: {
                                association_insertion_node: '#detail-association-insertion-point',
                                association_insertion_method: 'append'
                                }%>
                            </div>
                            <div class="mx-auto">
                                <%= f.fields_for :schedule_hoteldates do |schedule_hoteldate| %>
                                    <%= render "schedules/schedule_hoteldate_fields", f: schedule_hoteldate %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <%= f.submit '更新', class: "button is-success" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/schedules/index.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
        <h1 class="title">
            スケジュール一覧
        </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @schedules.each do |schedule| %>
                <div class="column is-4">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <%= link_to schedule_path(schedule) do %>
                                <%= attachment_image_tag schedule, :image, fallback: "no-image.jpeg" %>
                                <% end %>
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-48x48">
                                        <%= attachment_image_tag schedule.user, :profile_image, fallback: "no-image.jpeg", class: "profile_image" %>
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div class="title"><%=link_to schedule.user.username, user_path(schedule.user) %></div>
                                </div>
                            </div>
                            <div class="content">
                                <time><%= schedule.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/schedules/new.html.erb
  <section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                新規スケジュール作成
            </h1>
        </div>
    </div>
</section>

<% if @schedule.errors.any? %>
    <div class="notification is-danger">
        <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
        <ul>
            <% @schedule.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<section class="section">
    <div class="container">
        <div class="select-box">    
            <div class="columns is-centered">
                <div class="column is-6">
                    <%= form_with(model: @schedule, local: true) do |f| %>
                        <div class="field">
                            <%= f.label :title, "旅のタイトル", class: "label" %>
                            <%= f.text_field :title, :size=>"40",class: "input" %>
                        </div>
                        <table>
                            <tr>
                                <td>
                                    <%= f.label :body, "出発日", class: "label" %>
                                    <%= f.date_field :start_date, class: "input" %>
                                </td>
                                <td>
                                    <%= f.label :body, "帰着日", class: "label" %>
                                    <%= f.date_field :end_date, class: "input" %>
                                </td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td>
                                <%= f.label :num_p, "旅行する人数", class: "label" %>
                                <%= f.number_field :num_p, size: 50 %><label>人</label>
                                </td>
                                <td>
                                <%= f.label :fuel, "給油地域のガソリン代(km/L)", class: "label" %>
                                <%= f.number_field :fuel, size: 20 %><label>円</label>    
                                </td>
                            </tr>
                        </table>
                        <%= f.label :fuel_economy, "車の種類(軽自動車または普通自動車)", class: "label" %>
                        <%= f.select :fuel_economy, [["軽自動車", 18], ["普通自動車", 15]], include_blank: "車の種類を選択" %>
                        <div class="field">
                            <%= f.label :image, "写真", class: "label" %>
                            <%= f.attachment_field :image, class: "input" %>
                        </div>
                        <div class="plan-post">
                            <div class="recipe-ingredients">
                                <div id="detail-association-insertion-point"></div>
                                <div class="btn-right btn-adddate">
                                    <%= link_to_add_association "日付を追加", f, :schedule_hoteldates,
                                    class: "btn",
                                    data: {
                                    association_insertion_node: '#detail-association-insertion-point',
                                    association_insertion_method: 'append'
                                    }%>
                                </div>
                                <div class="mx-auto">
                                    <%= f.fields_for :schedule_hoteldates do |schedule_hoteldate| %>
                                        <%= render "schedules/schedule_hoteldate_fields", f: schedule_hoteldate %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                        <%= f.submit '投稿', class: "button is-success" %>
                    <% end %>
                </div> 
            </div>
        </div>
    </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <!-- フォーム入力欄 -->
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.jpeg" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <!-- user画像表示 -->
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpeg", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <!-- username表示 -->
                  <strong><%= @user.username %></strong>
                </td>
                <!-- current_user_idと@user.idが一致していればemailと編集ボタンを表示 -->
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <!-- userプロファイル表示 -->
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.schedules.each do |schedule| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to schedule_path(schedule) do %>
                  <%= attachment_image_tag schedule, :image, fallback: "no-image.jpeg" %>
                <% end %>
              </figure>
              <div class="center-title">
                <%= schedule.title %>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to schedule_path(schedule), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    スケジュールを確認
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_schedule_path(schedule), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      スケジュールを編集
                    <% end %>
                    <%= link_to schedule_path(schedule), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      スケジュールを削除
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= schedule.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>